[global]
   workgroup = WORKGROUP
   server string = LibraryIT Server
   security = user
   map to guest = never
   log file = /logs/libraryit.log
   max log size = 1000

[ebooks]
   path = /libraryit/ebooks
   valid users = @readonly @staff
   read only = no
   write list = @staff

[papers]
   path = /libraryit/papers
   valid users = @readonly @staff
   read only = no
   write list = @staff

[sourcecode]
   path = /libraryit/sourcecode
   valid users = @staff
   read only = yes
   browseable = no

[docs]
   path = /libraryit/docs
   valid users = @readonly @staff
   read only = yes
   write list = librarian
